services:
  web.api:
    image: web.api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    ports:
      - "5067:8080"

    user: "1000:1000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=db;Port=5432;Database=Multi-Ai-Chats;Username=postgres;Password=postgres

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Multi-Ai-Chats
    volumes:
      - ./.containers/AiChat_db:/var/lib/postgresql/data
    ports:
      - "5430:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: web.api
    command: bash -c "dotnet ef database update --verbose"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - aspnet_keys:/home/app/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=db;Port=5432;Database=Multi-Ai-Chats;Username=postgres;Password=postgres
      - DOTNET_ENVIRONMENT=Development
      - DOTNET_CLI_TELEMETRY_OPTOUT=1

volumes:
  aspnet_keys:
