services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
      target: watch
    ports:
      - "5067:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./src/Web.Api:/src/src/Web.Api
      - ./src/Application:/src/src/Application
      - ./src/Infrastructure:/src/src/Infrastructure
      - ./src/Domain:/src/src/Domain
      - ./src/SharedKernal:/src/src/SharedKernal

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=MultiChat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5430:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - ./.containers/redis:/data
    restart: on-failure
    command: redis-server --save 60 1 --loglevel warning

networks:
  default:
    name: monitoring-net