using System.Text;
using System.Text.Json;
using Application.Abstractions.Interfaces;
using Application.Services;
using Microsoft.Extensions.Configuration;

namespace Infrastructure.Services;

public class GeminiService : IAiModelService
{
    private readonly HttpClient _httpClient;
    private readonly string _apiKey;

    public GeminiService(IHttpClientFactory httpClientFactory, IConfiguration configuration)
    {
        _httpClient = httpClientFactory.CreateClient();
        // Set the correct base address for Google Gemini API
        _httpClient.BaseAddress = new Uri("https://generativelanguage.googleapis.com/");
        _apiKey = configuration["AI:Gemini:ApiKey"] ?? throw new ArgumentNullException("API key is missing");
    }

    public async IAsyncEnumerable<string> StreamResponseAsync(IEnumerable<MessageDto> history)
    {
        var validHistory = history.Where(m => !string.IsNullOrWhiteSpace(m.Content));
        var groupedContents = new List<object>();
        string? currentRole = null;
        var currentParts = new List<object>();

        foreach (var message in validHistory)
        {
            string role = message.IsFromAi ? "model" : "user";
            if (role != currentRole && currentParts.Any())
            {
                groupedContents.Add(new { role = currentRole, parts = currentParts.ToArray() });
                currentParts.Clear();
            }

            currentRole = role;
            currentParts.Add(new { text = message.Content });
        }

        if (currentParts.Any())
        {
            groupedContents.Add(new { role = currentRole, parts = currentParts.ToArray() });
        }

        if (!groupedContents.Any())
        {
            throw new InvalidOperationException("Conversation history cannot be empty.");
        }

        var requestBody = new
        {
            contents = groupedContents.ToArray(),
            generationConfig = new { temperature = 0.7, maxOutputTokens = 1024 }
        };

        Console.WriteLine($"Request body: {JsonSerializer.Serialize(requestBody)}");

        var request = new HttpRequestMessage(HttpMethod.Post,
            $"v1beta/models/gemini-1.5-flash:streamGenerateContent?key={_apiKey}")
        {
            Content = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json")
        };

        var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);
        response.EnsureSuccessStatusCode();

        // Read the entire response stream
        using var stream = await response.Content.ReadAsStreamAsync();
        using var reader = new StreamReader(stream);
        var fullResponse = await reader.ReadToEndAsync();

        // Parse the complete JSON array
        using var document = JsonDocument.Parse(fullResponse);
        bool yieldedAnyText = false;

        if (document.RootElement.ValueKind == JsonValueKind.Array)
        {
            foreach (var element in document.RootElement.EnumerateArray())
            {
                if (element.TryGetProperty("candidates", out var candidates) &&
                    candidates.GetArrayLength() > 0 &&
                    candidates[0].TryGetProperty("content", out var content) &&
                    content.TryGetProperty("parts", out var parts) &&
                    parts.GetArrayLength() > 0 &&
                    parts[0].TryGetProperty("text", out var textElement))
                {
                    var text = textElement.GetString();
                    if (!string.IsNullOrEmpty(text))
                    {
                        yieldedAnyText = true;
                        yield return text;
                    }
                }
            }
        }
        else
        {
            Console.WriteLine("Response is not a JSON array.");
        }

        if (!yieldedAnyText)
        {
            yield return "No response generated by the API.";
        }
    }
}