global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'web-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:7089']
    scheme: https
    tls_config:
      insecure_skip_verify: true

